### ISSUE TITLE
Doesn't work on Gigabyte x570 I aurous Pro Wifi

### ISSUE THREAD

**Issue by IGBC** [Philpax/borealis#10]
Probably not surprising but it doesn't seem to work on Gigabyte x570 motherboards.

:woman_shrugging: Eh... It was worth trying... I mean Aurous sounds a bit like aura... Right?

I wondered if they might be using the same controller and/or protocol, but the program never got as far as testing that, the failure was: `thread 'main' panicked at 'failed to locate AMD system SMBus', src/libcore/option.rs:1188:5` 

i2c-dev loaded, binary run as root.

You can close this issue when you are done laughing at me for trying.

**Comment by CalcProgrammer1** [comment]
Gigabyte's RGB Fusion 2.0 system uses USB.  See this issue:

https://gitlab.com/CalcProgrammer1/OpenRGB/issues/39

There is a project link near the bottom to a reportedly working implementation.

**Comment by IGBC** [comment]
Oh awesome, thanks!
